### ISSUE TITLE
Feedback Session 2

### ISSUE THREAD

**Issue by firasm** [ubco-W2022T2-data301/project-group-group08#1]
## Feedback for Group

1. What is your contracted grade?

- A

2. Are there are any group dynamics issues that we need to be aware of ? 

- No

3. Notes from [Islam/Saira] on Feedback on the analysis:

- [x] #2
- [x] #3
- [x] #4
- [x] #5
- [x] #6
- [x] #7
- [x] #8
- [x] #9

**Comment by jasonsuwito** [comment]
Completed Feedback Session 2
