### ISSUE TITLE
MS4 Feedback Session

### ISSUE THREAD

**Issue by sairafurqan** [ubco-W2022T2-data301/project-group-group08#10]
## Feedback for Group 8

1. Notes from [Saira] on Feedback on the analysis:

Analysis 1:

- [x] add titles to your visualizations.
- [x] use markdowns to add insights after your plots.
- [x] highlight your work for each milestone with a markdown title and add a conclusion that shows how did you answer your research question.

Analysis 2:

- [x] use markdowns to add insights after your plots.
- [x] highlight your work for each milestone with a markdown title and add a conclusion that shows how did you answer your research question.

Analysis 3:

- [x] use markdowns to add insights after your plots.
- [x] highlight your work for each milestone with a markdown title and add a conclusion that shows how did you answer your research question.

## Contracted Grade

1. What is your contracted grade?

- A

2. Are you on track to satisfy all the requirements of your contracted grade?

- Yes, Make changes mentioned in all of your open issues. [Please review the details of each contracted grade here](https://firas.moosvi.com/courses/data301/2022_WT2/project/introduction.html) and if you have questions, come see the instructor or the Project TAs for more details.

**Comment by jasonsuwito** [comment]
Completed MS4 Feedback Session
